### ISSUE TITLE
'Follow' posts no longer hidden

### ISSUE THREAD

**Issue by fejjj** [webdevsk/FB-Mobile-Clean-my-feeds#2]
Follow posts are no longer hidden.

**Comment by webdevsk** [comment]
Can you please share some screenshots or instances when this is happening? Point to note that this script only works with English language for now.

**Comment by fejjj** [comment]
Sure, I will do that next time I see it. Seems to happen intermittently.

**Comment by fejjj** [comment]
You may close this - I found that https://m.facebook.com/?sk=h_chr is now redirecting to https://facebook.com and still displaying the mobile webpage.  Since your script is only checking m.facebook.com, that is why it failed.

**Comment by webdevsk** [comment]
Added script detection for www.facebook.com. Should be fine now.
