### ISSUE TITLE
Reels/Bottom status bar

### ISSUE THREAD

**Issue by rac146** [webdevsk/FB-Mobile-Clean-my-feeds#3]
Great script, works really well and doesn't slow down the speed for the mobile site.

A few random things still appearing that are probably from recent facebook changes:
- Reels are appearing
- Suggested people/groups are appearing
- The bottom status bar that says "Get the best experience on the app" is appearing. 

The status bar can be removed via uBlock, but it would be pretty cool if these could all be managed by this script in the future

**Comment by webdevsk** [comment]
I have removed the bottom status bar prompting to install the app. I will post small updates with new filters whenever I face new facebook changes myself. Thanks for your feedback and suggestion.
